---
# tasks file for richardskumat.ansible_role_firewalld

- name: Include tasks specific to Centos 7.
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "7"

- name: Include tasks specific to Debian 10.
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "10"

- name: Run firewalld rules
  include_tasks: firewalld-rules.yml