---
# tasks file for richardskumat.ansible_role_firewalld

- name: Include tasks specific to Debian 11.
  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "11"

- name: Run firewalld rules
  include_tasks: firewalld-rules.yml