---
# handlers file for richardskumat.ansible_role_firewalld
- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: "{{ firewalld_service_state }}"
    enabled: "{{ firewalld_service_enabled }}"