---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-debian:buster-backports}"
    #image: "${MOLECULE_DISTRO:-centos:7}"
provisioner:
  name: ansible
  log: true
scenario:
  name: default
